apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: nsb
  labels:
    app: nsb
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - image: "mpmsimo/nsb:cron-job"
            imagePullPolicy: IfNotPresent
            name: application
            resources:
              limits:
                cpu: 1
                memory: 1024M 
              requests:
                cpu: 500m
                memory: 512M
